

#define THREAD_GROUP_SIZE_X 1
#define THREAD_GROUP_SIZE_Y 1
#define THREAD_GROUP_SIZE_Z 1

#pragma kernel PassThrough

StructuredBuffer<float4x4> worldMatrixBufferInput;
AppendStructuredBuffer<float4x4> worldMatrixBufferOutput;

[numthreads(THREAD_GROUP_SIZE_X, THREAD_GROUP_SIZE_Y, THREAD_GROUP_SIZE_Z)]
void PassThrough(uint3 id : SV_DispatchThreadID)
{
    float4x4 inMatrix = worldMatrixBufferInput[id.x];
    worldMatrixBufferOutput.Append(inMatrix);
}
